- name: Configure timezone
  file:
    src: /usr/share/zoneinfo/Europe/Berlin
    dest: /etc/localtime
    state: link
- name: Interpret hardware clock as UTC
  command:
    cmd: hwclock --systohc
    creates: /etc/adjtime

- name: Generate locale.gen
  blockinfile:
    path: /etc/locale.gen
    insertbefore: BOF
    content: "{{ lookup('file', 'files/locale.gen.block', rstrip=false) }}"
  notify: locale-gen
- name: Configure locale
  copy:
    dest: /etc/locale.conf
    content: "{{ lookup('file', 'files/locale.conf') }}\n"

- name: Configure pacman options
  blockinfile:
    path: /etc/pacman.conf
    insertafter: '^\[options\]$'
    block: "{{ lookup('file', 'files/pacman.conf.block') }}"
- name: Enable multilib repo
  blockinfile:
    path: /etc/pacman.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK (multilib)"
    insertbefore: '^#\[multilib\]$'
    block: "{{ lookup('file', 'files/pacman.conf-multilib.block') }}"
- name: Use RWTH server for pacman
  copy:
    dest: /etc/pacman.d/mirrorlist
    content: "{{ lookup('file', 'files/mirrorlist') }}\n"

- name: Configure hostname
  copy:
    dest: /etc/hostname
    content: "{{ myhostname }}\n"
- name: Ensure hosts contains localhost
  blockinfile:
    path: /etc/hosts
    insertafter: '^# See hosts\(5\) for details\.$'
    content: "{{ lookup('template', 'templates/hosts.j2') }}"
- name: Update system
  pacman:
    update_cache: yes
    upgrade: yes
- name: Install base packages
  pacman:
    name: "{{ lookup('file', 'files/packages.txt').splitlines() | list }}"
