- name: Clone dotfiles
  command:
    chdir: '~'
    cmd: git clone 'https://gitlab.com/vimpostor/dotfiles.git' "{{ dotfiles_dir }}"
    creates: "{{ dotfiles_dir }}"
- name: Install dotfiles
  command:
    chdir: "{{ dotfiles_dir }}"
    cmd: ./link.sh -y
    creates: '~/.zshrc'
- name: Create XDG directories
  command:
    chdir: '~'
    cmd: mkdir Desktop Downloads Music Pictures Videos
    creates: '~/Downloads'
