- name: Install pro-audio packages
  pacman:
    name: "{{ lookup('file', 'files/packages.txt').splitlines() | list }}"
- name: Add to realtime group
  user:
    name: magnus
    groups: realtime
    append: yes
