- name: Install dev packages
  pacman:
    name: "{{ lookup('file', 'files/packages.txt').splitlines() | list }}"
- name: Add to wireshark group
  user:
    name: magnus
    groups: wireshark
    append: yes
