- name: Install productivity packages
  pacman:
    name: "{{ lookup('file', 'files/packages.txt').splitlines() | list }}"
- name: Enable NetworkManager
  systemd:
    name: NetworkManager.service
    enabled: yes
- name: Enable sddm
  systemd:
    name: sddm.service
    enabled: yes
